name: belajar_dart_packages_library
description: This is library from Programmer Zaman Now
version: 1.5.0
homepage: https://www.programmerzamannow.com
repository: https://github.com/BuvanAlfarezy/belajar_dart_packages_library

environment:
  sdk: '>=2.16.1 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
